create table author (id integer not null auto_increment, author_name varchar(255), primary key (id));
create table book (id integer not null auto_increment, book_name varchar(255), detail varchar(255), img varchar(255), price varchar(255), quantity integer not null, size varchar(255), total_page varchar(255), author integer, category integer, publisher integer, primary key (id));
create table cart (id integer not null auto_increment, cart_status BIT, date_create DATE, customer_id integer, primary key (id));
create table cart_detail (id integer not null auto_increment, cart_detail_quantity integer, book_id integer, cart_id integer, primary key (id));
create table category (id integer not null auto_increment, category_name varchar(255), primary key (id));
create table customer (id integer not null auto_increment, address varchar(255), customer_name varchar(255), phone varchar(255), customer_username VARCHAR(30), primary key (id));
create table publisher (id integer not null auto_increment, publisher_name varchar(255), primary key (id));
create table role (role_id integer not null auto_increment, role_name varchar(255), primary key (role_id));
create table user (username VARCHAR(30) not null, flag BIT, password varchar(255), primary key (username));
create table user_role (user_role_id integer not null auto_increment, role integer, username VARCHAR(30), primary key (user_role_id));
alter table book add constraint FK9wwmvcc520honrafnyi2gkdj4 foreign key (author) references author (id);
alter table book add constraint FKa58ia1r4ptov8h8agr0itfo67 foreign key (category) references category (id);
alter table book add constraint FKtf8snvmfw8ixn04kp8a5fhain foreign key (publisher) references publisher (id);
alter table cart add constraint FKdebwvad6pp1ekiqy5jtixqbaj foreign key (customer_id) references customer (id);
alter table cart_detail add constraint FKflpu1psdex9le27p7owju2piw foreign key (book_id) references book (id);
alter table cart_detail add constraint FKrg4yopd2252nwj8bfcgq5f4jp foreign key (cart_id) references cart (id);
alter table customer add constraint FKa1pjteg1g3o05ax0xp3o9l19b foreign key (customer_username) references user (username);
alter table user_role add constraint FK26f1qdx6r8j1ggkgras9nrc1d foreign key (role) references role (role_id);
alter table user_role add constraint FKnircs1pyebpo0eucojumm0aed foreign key (username) references user (username);